services:
  api:
    build: .
    container_name: elearning_api
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Default=Host=db;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
      - JWT_KEY=bXlKd3RLZXk=
      - JWT_ISSUER=elearning
      - JWT_AUDIENCE=elearning_users
      - Jwt__ExpiresMinutes=60
      - Jwt__RefreshDays=14
      - POSTGRES_DB=elearning2db
      - POSTGRES_USER=elearning2user
      - POSTGRES_PASSWORD=superelearner2
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:16
    container_name: elearning_pg
    restart: unless-stopped
    environment:
      POSTGRES_DB: elearning2db
      POSTGRES_USER: elearning2user
      POSTGRES_PASSWORD: superelearner2
    ports:
      - "5432:5432"
    volumes:
      - elearning_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U elearning2user -d elearning2db"]
      interval: 5s
      timeout: 3s
      retries: 10
volumes:
  elearning_data:
